name: AKS Login
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  aks_login:
    runs-on: ubuntu-latest
    steps:
    
      - name: Install AZ CLI
        run : |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            az --version
            
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        
        
